name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: make
        run: make

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: thread_socket
          tag_name: V0.1
          release_name: Release V0.1
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
